server {
    listen 80;
    listen [::]:80;
    server_name bot.hold-bet.com;
    location /.well-known/acme-challenge/ { root /var/www/html; }
    location / { return 301 https://bot.hold-bet.com$request_uri; }
}
